### ISSUE TITLE
BootCv issue in Score function

### ISSUE THREAD

**Issue by yilunsun** [tagteam/riskRegression#12]
Hi,

When setting the split.method to BootCv in the Score function, I got error message "Error in { : task 1 failed - "missing value where TRUE/FALSE needed" right after the progress bar completes. The error is gone when not using internal validation. The sample code from the manual can serve as a replicable example:

library(survival)
set.seed(18)
trainSurv <- sampleData(400,outcome="survival")
cox1 = coxph(Surv(time,event)~X1+X2+X7+X9,data=trainSurv, y=TRUE, x = TRUE)
cox2 = coxph(Surv(time,event)~X3+X5+X6,data=trainSurv, y=TRUE, x = TRUE)

x2= Score(list("Cox(X1+X2+X7+X9)"=cox1,"Cox(X3+X5+X6)"=cox2),
formula=Surv(time,event)~1,data=trainSurv,conf.int=TRUE,times=c(5,8),
split.method="bootcv",B=100)

**Comment by tagteam** [comment]
Thanks for pointing this out. The foreach loop did not export data.table. Should be fixed now with version 2020.8.13
