### ISSUE TITLE
getInfluenceCurve.AUC.survival has integer overflow problem

### ISSUE THREAD

**Issue by NikKrieger** [tagteam/riskRegression#13]
`riskRegression:::getInfluenceCurve.AUC.survival` performs the operation `n * n` twice. Since `n` (one of the function's formal arguments) is an integer, an integer overflow error occurs if `n` is modestly large (viz., >46340). The harm is that the AUC's resulting confidence interval will be (NA, NA).

This can be remedied by converting `n` to double or by using `n ^ 2L` instead of `n * n`.

It's possible that this same error might occur in other functions.

**Comment by tagteam** [comment]
thanks for pointing this out. however, I cannot reproduce the problem. even with values much larger than 46340 I get a non-NA result

> n <- 999128146340
> n*n
[1] 9.982571e+23

please provide an example where the AUC is NA.

**Comment by tagteam** [comment]
Thanks for pointing this out. I have just pushed a quick fix of the Score function (and will check the remaining functions ASAP) please let me know if you get a non-NA result for AUC with the new version.

**Comment by NikKrieger** [comment]
I don't get the integer overflow warning anymore and I got non-NA results. Thank you.

**Comment by NikKrieger** [comment]
For anyone unable to update the package, running this before AUC calculation patches the problem:

```r
trace(
  what = riskRegression:::getInfluenceCurve.AUC.survival,
  tracer = quote(n <- as.numeric(n))
)
```
