### ISSUE TITLE
Allow us to use foreach strategies as registered in the main script in Score

### ISSUE THREAD

**Issue by erikvona** [tagteam/riskRegression#14]
Currently, if we use `Score` and want to parallelize, we need to either let `Score` create a cluster for us or pass in a cluster.

This is quite limiting for me, as I'd like to work with futures and the doFuture packages and the additional ways to parallelize tasks that come with it. It also disallows other parallel backends, such as MPI via the doMPI package

A very simple solution would be to allow us to specify that we've registered our parallel strategy ourselves, and do nothing in that case.

The change would be as simple as adding another option to the `parallel` argument. Since that won't get recognized in the `switch`, the registered approach for `%dopar%` will get used. So the only adjustment would be, in the function call:

`parallel=c("no","multicore","snow"),`

to:

`parallel=c("no","multicore","snow", "as.registered"),`

This would allow us to pass "as.registered" here, which would then be allowed by match.args, but not do anything in the `switch` that registers the parallel backend, which would cause `%dopar%` to use the registered parallel backend in the global scope, or issue a warning if none is registered and execute sequentially.

Additionally, I'd like the process to be adjusted when a cluster is passed or `as.registered` is specified to ignore the `ncpus` argument (very counter-intuitive that when I'm setting up the cluster I still need to specify ncpus > 1):

      if (ncpus<=1 & is.null(cluster) & parallel != "as.registered") {
            parallel <- "no"
        }

**Comment by tagteam** [comment]
this seems to be a great idea. I just pushed a new version of Score with the two lines. could you please 
a) test if this works
b) send example code preferably using simulated data which I put into the help page
should I add future and doFuture as suggested packages?
thanks

**Comment by tagteam** [comment]
cluster is not a variable, so I changed to 
  if (ncpus<=1 && parallel != "as.registered") {
        parallel <- "no"
    }
ok?

**Comment by erikvona** [comment]
Thanks a lot for the quick reply and action!

I meant `if (ncpus<=1 & is.null(cl) & parallel != "as.registered") {`. That avoids ignoring the cluster if ncpus is not specified. Sorry for confusing the variable names.

Here is a generic example of using future and doFuture, works great with the current version:

```
library(riskRegression)
library(future)
library(foreach)
library(doFuture)
library(survival)
# Register all available cores for parallel operation
plan(multiprocess, workers = availableCores())
registerDoFuture()

trainSurv <- sampleData(400,outcome="survival")
cox1 = coxph(Surv(time,event)~X1+X2+X7+X9,data=trainSurv, y=TRUE, x = TRUE)
# Bootstrapping on multiple cores
x1 = Score(list("Cox(X1+X2+X7+X9)"=cox1),
           formula=Surv(time,event)~1,data=trainSurv, times=c(5,8), 
           parallel = "as.registered", split.method="bootcv",B=100)
```

Of course, this mainly offers added speed if you're running heavy models and distributing across computers, e.g. running random forests on a cluster and a large dataset using future.batchtools. Else existing solutions using snow/multicore might be sufficient. But allowing the user to choose any backend gains us a lot of flexibility.

As for adding it to the suggested packages, I leave that up to you, as it now works with any parallel foreach backend (also doMPI/doRedis for distributed computing), and there are many, there's no specific reason to pick doFuture.

**Comment by tagteam** [comment]
great. everything is in there now. thank you very much.
