### ISSUE TITLE
riskRegression and joint models

### ISSUE THREAD

**Issue by BenGoudsmit** [tagteam/riskRegression#19]
Dear riskRegression team,

I am a fan of your beautiful package.
For survival analysis, I have been using joint models lately.
Could riskRegression possibly be extended to work with these models?
E.g. like the JM or JMbayes software from d.rizopoulos?

Kind regards,

Ben

**Comment by tagteam** [comment]
Hi Ben 

Yes, all it takes is a predictRisk.JM and predictRisk.JMbayes function. The required arguments are newdata for uncensored binary outcome data, newdata and times for right censored survival outcome and newdata, times, cause for competing risk. I don't know the JM software, so it would be most fruitful if you give it a try and let me know if you have trouble getting this to work. cheers Thomas

**Comment by BenGoudsmit** [comment]
What I did get to work is comparing JM software and riskRegression AUCs based on JM software-generated survival probabilities (function survfitJM). There are significant differences in these AUCs, therefore I will have a try at extending a predictRisk or predictSurvProb function.

**Comment by tagteam** [comment]
ok. let me know when you are done :)
