### ISSUE TITLE
IPCW clarification

### ISSUE THREAD

**Issue by mattwarkentin** [tagteam/riskRegression#22]
Hi @tagteam,

I am wondering if you could provide some clarification in regards to the `ipcw()` function. I realize this could have been posted at the `{pec}` repository, but this repo seemed more active.

I know this function is primarily meant for internal use, but I am trying to better understand it anyway for my own interest/learning.

The name of the function is `ipcw()` which indicates its use for inverse-probability of censoring weights. However, the title of the function in the documentation is **Estimation of censoring probabilities**, meanwhile the description of the function is *This function is used internally to obtain inverse of the probability of censoring weights.* Lastly, the documentation return value indicates that the function returns `IPCW.times -> Estimated weights at times`.

My confusion is that none of those seem to be strictly true. The function itself seems to return the **probabilities of NOT being censored** and not weights. Is this correct?

In other words, the function doesn't seem to return censoring probabilities (this may just be semantics), as the title suggests, or even inverse probability weights (which would in fact be the inverse of `IPCW.times`). Am I on the right track?

So in order to actually obtain the IPCW, one would need to compute these as
``` r
library(survival)
library(riskRegression)
library(pec)
library(prodlim)

xx <- sampleData(1000, outcome = "survival")

pl <- prodlim(Hist(time, event) ~ 1, data = xx, reverse = TRUE)

# Prob. of not being censored at t = 10
predict(pl, times = 10, newdata = xx, type = "surv")
#> [1] 0.3567289

ii <- ipcw(
  Hist(time, event) ~ 1,
  xx,
  method = "marginal",
  times = 10
)

# Same number as above
ii$IPCW.times
#> [1] 0.3567289

# IPCW
1 / ii$IPCW.times
#> [1] 2.803249
```

Thank you for your help!

**Comment by tagteam** [comment]
Yes, this is all just a semantic problem. To clarify we need to use mathematics and define for given baseline covariate X: the probability of censoring until time t as 1-G(t|X)=P(C<=t|X), the inverse probability of censoring as G(t|X) = P(C>t|X) and the inverse probability of censoring weight as 1/G(t|X). The function calculates G(T_i-|X_i), i.e., the value of G just before time T_i as well as for a given vector of time points (t_1,...,t_K) the values G(t_k|X_i) for all subjects i.

**Comment by mattwarkentin** [comment]
Thanks for the response. Just so I'm clear on the terminology:

- Probability of censoring = P(C <= t | X)

- Inverse probability of censoring = P(C > t | X) or 1 - P(C <= t | X)
  + Could also be called the probability of NOT being censored

- Inverse probability of censoring weight = 1 /  P(C > t | X)

Is this correct?

**Comment by tagteam** [comment]
you just copied the terms from my message. the mathematics are correct. I am not native English speaking and cannot tell whether the language is correct.  but, maybe probability of NOT YET being censored is more correct. cheers
