### ISSUE TITLE
score with survSplit data

### ISSUE THREAD

**Issue by BenGoudsmit** [tagteam/riskRegression#23]
Dear Thomas,

I want to use your wonderful package to score performance in survsplitted data.
Is this possible?
Consider:
```
survcut <- survSplit(data = survtx,
                     cut = c(0.5, 1, 3)*365.25, 
                     start = "start",
                     end = "time",
                     event = "death",
                     episode = "tgroup")
```
With time-varying predictor age:
```
survcut <- survcut %>% mutate(
  age_t1 = age*(tgroup==1),
  age_t2 = age*(tgroup==2),
  age_t3 = age*(tgroup==3),
  age_t4 = age*(tgroup==4))
```
From this, a training (traincut) and testing (testcut) dataset are generated.
And Cox model is fit in training data:
```
cox<- coxph(Surv(start, time, death)~ 
                  age_t1+age_t2+age_t3+age_t4,
                  data=traincut, model=TRUE, x = TRUE)
```
Which I would like to score in testing data with something like:
```
score_allcox <- Score(list("Cox"=cox),
                      formula=Surv(time,death)~1,data=testcut,
                      conf.int=TRUE,times=5*365.25)
score_allcox
```
Which warns me:

> Warning message:
> In predictCox(object = object, newdata = newdata, times = times,  :
>   The current version of predictCox was not designed to handle left censoring 
> The function may be used on own risks

And the result seems unreliable. Is there a way to handle these survSplitted data to score at a specific time with you package?

Thanks in advance.

**Comment by tagteam** [comment]
We would need a reference that describes the performance parameters that we would like to estimate in the survsplit situation. But, what exactly do you mean by "at a specific time"? do you mean specific baseline/landmark time or specific prediction time horizon? in my experience, a prediction problem needs both, the time where the prediction is given to the patient (baseline/landmark) and the time attached to the predicted risk, e.g., 5-year risk of death.
