### ISSUE TITLE
Pseudovalues returned by Score() for competing risks

### ISSUE THREAD

**Issue by edbonneville** [tagteam/riskRegression#24]
Dear @tagteam ,

Thank you for the excellent package! I wanted to report a possible issue with the pseudovalues returned by `Score(..., plots = "calibration")` when validating a competing risks model. 

## Description

In short: I believe the pseudovalues currently returned in `<Score_object>$Calibration$plotframe$pseudovalue`  (calculated [here](https://github.com/tagteam/riskRegression/blob/5e18c1800827c31ba9789d5fa151c8ffa64a9566/R/Score.R#L875)) are the result of a jacknife procedure where the marginal cumulative incidences are calculated by treating censored observations as a competing event.

As far as I can tell the problem originates [here](https://github.com/tagteam/riskRegression/blob/5e18c1800827c31ba9789d5fa151c8ffa64a9566/R/Score.R#L538) (and then [here](https://github.com/tagteam/riskRegression/blob/5e18c1800827c31ba9789d5fa151c8ffa64a9566/R/getResponse.R#L56)), in that `prodlim::Hist()` evaluated on the validation data (after being unclassed) will return a matrix where the 'event' column now codes censored observations as number of competing causes + 1, instead of zero. The marginal model used to create the pseudovalues is thus fit using this event indicator which treats censoring as competing event.

## Example

``` r
library(survival)
library(prodlim)
library(riskRegression)
#> Warning in .recacheSubclasses(def@className, def, env): undefined subclass
#> "numericVector" of class "Mnumeric"; definition not updated
#> riskRegression version 2021.03.17

# Simulate competing risks data
set.seed(4321)
n <- 1000
dat <- SimCompRisk(N = n)
validation_dat <- SimCompRisk(N = n)

# Build model and validate (for cause 1) at time = 10
horizon <- 10
primary_event <- 1

mod <- CSC(Hist(time, event) ~ X1 + X2, data = dat)
score_validation <- Score(
  list("model" = mod),
  formula = Hist(time, event) ~ 1,
  data = validation_dat,
  cause = primary_event,
  times = horizon,
  plots = "calibration"
)

# Get pseudo values df 
pseudos_df <- score_validation$Calibration$plotframe

# Event indicator used to make pseudovalues should not have 3 as censoring
# (otherwise treated as competing event)
pseudos_df[, c("status", "event")]
#>       status event
#>    1:      0     3
#>    2:      1     2
#>    3:      1     2
#>    4:      1     1
#>    5:      0     3
#>   ---             
#>  996:      1     2
#>  997:      0     3
#>  998:      1     2
#>  999:      0     3
#> 1000:      0     3
pseudos_df$event_actual <- ifelse(pseudos_df$event == 3, 0, pseudos_df$event)

# Prepare marginal fits
margFit <- prodlim(Hist(time, event) ~ 1, data = pseudos_df)
margFit_actual <- prodlim(Hist(time, event_actual) ~ 1, data = pseudos_df)

# One treats censoring as competing risks (since cens.code not adjusted in Hist())
attr(margFit$model.response, "states")
#> [1] "1" "2" "3"
attr(margFit_actual$model.response, "states")
#> [1] "1" "2"

# Now check the pseudovalues
pseudovals_current <- drop(jackknife(margFit, horizon, primary_event))
pseudovals_actual <- drop(jackknife(margFit_actual, horizon, primary_event))

all.equal(pseudos_df$pseudovalue, pseudovals_current)
#> [1] TRUE
all.equal(pseudos_df$pseudovalue, pseudovals_actual)
#> [1] "Mean relative difference: 0.5028651"
```
(The `pseudovals_actual` above would be the pseudovalues I would think should normally be returned)

## Possible fixes

In order to not edit `prodlim::Hist()` directly, a possible idea could be to use the "states" attribute on the object returned by `getResponse()` and then set `Hist(..., cens.code = max(states) + 1)` when calculating the marginal fit? Though I am not sure in how many places this would need to be done..

Thank you for your time/consideration!

**Comment by tagteam** [comment]
thanks for pointing this out. I fixed the bug  and pushed a new version 2021-06-30. please check

**Comment by edbonneville** [comment]
Have now checked it - looks good! Thank you for fixing so quickly.
