### ISSUE TITLE
Bootstrap AUC confidence intervals without retraining

### ISSUE THREAD

**Issue by millgreg** [tagteam/riskRegression#25]
Hi,
I was wondering if it is possible to use the score function to calculate AUC confidence intervals using bootstrap on test data without retraining the model? As far as I can tell there is only one bootstrap possibility using bootcv as cross-validation method, which would retrain the object on the provided data.frame in "data".

Thanks!

**Comment by tagteam** [comment]
Hi, 
not yet. but, we are currently testing the small sample properties of the various standard errors of the Score function and will consider the subsampling bootstrap as a new option. thanx for your interest.

cheers
