### ISSUE TITLE
autoplot method for Brier Score & AUC for Score() object

### ISSUE THREAD

**Issue by jemus42** [tagteam/riskRegression#26]
During Monday's workshop the topic of an autoplot method came up to improve display of Brier Score & AUC plots as currently implemented by `plotAUC` and `plotBrier`.

I naively assumed it can't be *that* hard so I tried a minimal example:

``` r
library(ggplot2)
library(riskRegression)
#> riskRegression version 2021.10.10
library(survival)
data("Melanoma")

fit.csc_cox <- CSC(Hist(time, status) ~ ici + invasion + epicel + ulcer + logthick + sex + age, data = Melanoma)
fit.csc_stratcox <- CSC(Hist(time, status) ~ ici + invasion + epicel + ulcer + logthick + age * strata(sex), data = Melanoma)
fit.rf <- randomForestSRC::rfsrc(
  Surv(time, status) ~ ici + invasion + epicel + ulcer + logthick + sex + age, data = Melanoma
)

scores <- Score(
  list(Cox = fit.csc_cox, StratCox = fit.csc_stratcox, RF = fit.rf),
  data = Melanoma,
  formula = Hist(time, status) ~ 1,
  times = seq(0, 3500, 100)
)

autoplot.Score <- function(object, type = c("Brier", "AUC"), conf.int = FALSE) {
  type <- match.arg(type, choices = type)

  # NYI: Contrasts
  score_df <- object[[type]][["score"]]
  # AUC will be NaN early on, drop the points to avoid ggplot warning
  score_df <- score_df[is.finite(score_df[[type]]), ]

  p <- ggplot2::ggplot(
    score_df,
    ggplot2::aes_string(x = "times", y = type, color = "model", fill = "model")
  ) +
    ggplot2::geom_path()

  # NYI: Confidence interval

  p

}

autoplot(scores, type = "Brier")
```

![](https://i.imgur.com/bxtgtiw.png)

``` r
autoplot(scores, type = "AUC")
```

![](https://i.imgur.com/0NIawtC.png)

<sup>Created on 2021-10-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

So now I'm reasonably confident I can recreate the majority of the functionality of the previous two functions (I'm aware that my minimal example is missing quite a few knobs), but before I start preparing a PR I'd like to check in and make some assumptions:

- I'd prefer to leave visual styling out of the function arguments, since `autoplot` will return a `ggplot` object the user is free to tack on any `theme()` they choose. Basic options for linetypes or color palettes are a different topic and should probably be arguments to the function, I guess?
- `scores$Brier` and `scores$AUC` contain all the relevant information needed for the plots in tabular form, correct? From skimming the code for the other two function it looks like I won't need to dig very deep into other internals, right?

Please let me know if there's something important I'm missing here - otherwise I'll get started in the next few days and prepare a PR with usage examples + output :)

**Comment by jemus42** [comment]
Wait a minute... https://github.com/tagteam/riskRegression/blob/master/R/autoplot.Score.R already exists 😅

**Comment by tagteam** [comment]
yes, I forgot ... sorry! the documentation is rather poor right now. generally I feel that it would be nicer to have separate autoplot functions for AUC and Brier, respectively. how would you do this?

**Comment by jemus42** [comment]
Since `autoplot` would work on the `Score` object, i.e. object of type `Score`, I'm not sure that's (easily) possible unfortunately since it's a generic and requires different classes for different methods. 

One (maybe clunkier) way might be to give `scores$Brier` and `scores$AUC` distinct classes so one could use `autoplot(scores$Brier)` and similarly for AUC, but I'm not sure if that's more convenient from a user's perspective.  
Documentation of both `Score()` and `autoplot.*` methods would need to provide some guidance for users either way I guess.

**Comment by tagteam** [comment]
ok.
