### ISSUE TITLE
Add a pkgdown site

### ISSUE THREAD

**Issue by jemus42** [tagteam/riskRegression#27]
I'd like to prepare a PR to add a [pkgdown](https://pkgdown.r-lib.org/) website for the package.  
I do so religiously for my own packages and think it's good practice in general as it improves discoverability and makes it very easy (and reasonably pleasant/pretty) for potential users to discover what's inside the tin, browse examples and vignettes, and lower the barrier from "oh, look another package" to "oh, nice a package _I would like to use_.

The basic setup would include:

1.  A `_pkgdown.yaml` file to declare basic metadata (name, short description, ...)
2. A GitHub action file to render the site after each commit and push the output to the `gh-pages` branch from which it can be served with GitHub Pages
3. Enabling GitHub pages in the repository settings and pointing it to the `gh-pages` branch (this will have to be done by a maintainer/repo admin)

I can set up 1 + 2 in my fork for preview and if you like it there would only be 3) to do.  

Continued maintenance of a pkgdown site is, in my experience, very easy and hands-off, unless you decide on completely over-engineering all the fiddly bits (which is fun, but not necessarily a good use of time, I guess).

Let me know if there's any interest :)

**Comment by tagteam** [comment]
yes, please go ahead

**Comment by jemus42** [comment]
Nice :) Since pkgdown 2.0 is on the horizon this week I'll wait for that to come out so the site will have all the new shinies.
