### ISSUE TITLE
Error rowSumsCrossprod(htij1, 1 + MC.Ti.Cases, 0): Not a matrix

### ISSUE THREAD

**Issue by rafanmir** [tagteam/riskRegression#30]
Hi,
I'm trying to use the Score() function but ended up with this error:
Error in rowSumsCrossprod(htij1, 1 + MC.Ti.Cases, 0): Not a matrix
I tried to use the function with a Fine-Gray model with the FGR function (which worked well). I tried to look for this error but couldn't find nothing about it. Would it be possible that this is a bug?
Thanks

**Comment by tagteam** [comment]
thanks for reporting. please provide a data example so we can reproduce the error.

**Comment by rafanmir** [comment]
Hi, I'll find a way of simulating a dataset from the one I have as I'm working with sensitive data. I modified my dataset today, removed all factor variables, and the function worked. Is this a condition for the function to work?

**Comment by tagteam** [comment]
no, it's not a condition.
