### ISSUE TITLE
Memory issues with Score() function

### ISSUE THREAD

**Issue by ellessenne** [tagteam/riskRegression#31]
Hi,
I seem to run into memory issue with what I thought was a relatively small dataset (100000 rows) when running the `Score()` function, see e.g. the code below:

``` r
library(riskRegression)
#> Warning in .recacheSubclasses(def@className, def, env): undefined subclass
#> "numericVector" of class "Mnumeric"; definition not updated
#> riskRegression version 2021.10.10
library(rms)
#> Loading required package: Hmisc
#> Loading required package: lattice
#> Loading required package: survival
#> Loading required package: Formula
#> Loading required package: ggplot2
#> 
#> Attaching package: 'Hmisc'
#> The following objects are masked from 'package:base':
#> 
#>     format.pval, units
#> Loading required package: SparseM
#> 
#> Attaching package: 'SparseM'
#> The following object is masked from 'package:base':
#> 
#>     backsolve
library(prodlim)
set.seed(18)
trainSurv <- sampleData(100000, outcome = "survival")
cox1 <- coxph(Surv(time, event) ~ X3 + X5 + X6, data = trainSurv, y = TRUE, x = TRUE)
xs <- Score(
  list("Cox(X3+X5+X6)" = cox1),
  formula = Surv(time, event) ~ 1, 
  data = trainSurv, times = 1
)
#> Error in IC_Nelson_Aalen_cens_time(time = data$time, status = data$status): Mat::init(): requested size is too large; suggest to enable ARMA_64BIT_WORD
xs
#> Error in eval(expr, envir, enclos): object 'xs' not found
```

<sup>Created on 2022-02-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I was wondering, is that really too big of a dataset for this?
I get this error on a macOS laptop (with 16 Gb or RAM) and on a compute server with more than that.

Thanks,

Alessandro

**Comment by tagteam** [comment]
bad news: yes, too big. the problem is the implementation of the standard error in the right censored data which uses a n times n matrix. try matrix(double(1000000*1000000,nrow=1000000) on your machine ... 

good news: you are not the first to report and we are currently working on a completely new memory efficient algorithm for the influence function in the censored case. until then, you can use se.fit=0L and the bootstrap to get standard errors.

**Comment by ellessenne** [comment]
I see, that's what I thought - thanks very much for the quick feedback!
And thanks for the suggestion of using the bootstrap instead to compute standard errors for the different metrics, I'll do it this way for the time being.
Best,

Alessandro
