### ISSUE TITLE
Error in Score() function

### ISSUE THREAD

**Issue by Fariba-tohidinezhad** [tagteam/riskRegression#33]
Dear Thomas,

Thanks for the impressive "riskRegression" package and its comprehensive manual.
I am trying to call the riskRegression::Score() function to get the auc measures. However, I am stopped by the following error, which seems to be evoked from line 141 in Score.R (data[, `:=`(ID, 1:N)]):

Code:
fit1 <- ARR(Hist(Time_to_BM,BM_CR)~Age+WHO_PS,data=dt.raw,cause=1)
fit2 <- ARR(Hist(Time_to_BM,BM_CR)~Age+WHO_PS+Chemo_Cycle,data=dt.raw,cause=1)

x <- Score.list (list(fit1, fit2),
           data=dt.raw,
           formula=Hist(Time_to_BM,BM_CR)~1,
           cause=1,
           measure="auc")

Error:
Supplied 3 items to be assigned to 109 items of column 'ID'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.
In addition: Warning message:
In 1:N : numerical expression has 109 elements: only the first used

It seems that it doesn't treat N as a single numeric value.
I would appreciate if you could help me to address this issue.

Regards,
Fariba

**Comment by tagteam** [comment]
I cannot reproduce this because you did not provide the data dt.raw. can you create a reproducible example? perhaps there are missing values in the data?

**Comment by Fariba-tohidinezhad** [comment]
Thanks for your quick reply, Thomas.
The dataset is imputed already, so there are no missing values. I have changed the name of the dataset for transparency. Below is the script I am trying to run to get the roc of fit1 and fit2 models:


```
library (riskRegression)
library (prodlim)
library (survival)

dt=read.csv("C:\\R_Data\\SCLC\\NVGT.csv")

head (dt)

fit1 <- ARR(Hist(time,status)~Age+WHO_PS,data=dt,cause=1)
fit2 <- ARR(Hist(time,status)~Age+WHO_PS+Chemo_Cycle,data=dt,cause=1)

roc = riskRegression::Score(
  object = list(fit1,fit2),
  data = dt,
  formula = Hist(time,status,cens.code=1) ~ 1,
  times = 12,
  plots = "ROC"
)
```
dt includes the following variables:

Age: (numeric)
Gender: (0 female, 1 male)
WHO_PS or performance status: (1: good, 2: moderately disables, 3: limited active)
Chemo or chemotherapy: (0: no, 1: yes)
Chemo_Cycle or the number of chemotherapy cycles: (1: 1,2, or 3 cycles- 2: 4 or 5 cycles- 3: 6 cycles)
status: (0: censored, 1: event of interest, 2: competing event)
time (in months): maximum followup for censored cases and event for the patients who experienced the events (1 or 2).

` head (dt)`

Age Gender WHO_PS Chemo Chemo_Cycle status time
43      0      0     1           3      2 53.5
44      1      0     1           2      1  4.3
49      1      1     0           3      2 11.7
49      1      1     1           3      2  6.1
50      1      1     1           3      2 13.8
51      1      1     1           1      1  6.8

Please, let me know if you need further details.

**Comment by tagteam** [comment]
thanks, I still cannot reproduce the error. which version of riskRegression, data.table, etc. (sessionInfo()) do you use? this code here runs without errors on my machine:
library(riskRegression)
library(data.table)
library(prodlim)
library(survival)
set.seed(4)
dt <- sampleData(208)[,.(time,event,X6,X1,X2,X3,X4)]
setnames(dt,c("time","status","Age","Gender","WHO_PS","Chemo","Chemo_Cycle"))
fit1 <- ARR(Hist(time,status)~Age+WHO_PS,data=dt,cause=1)
fit2 <- ARR(Hist(time,status)~Age+WHO_PS+Chemo_Cycle,data=dt,cause=1)
roc = riskRegression::Score(
  object = list(fit1,fit2),
  data = dt,
  formula = Hist(time,status,cens.code=1) ~ 1,
  times = 12,
  plots = "ROC"
)

**Comment by Fariba-tohidinezhad** [comment]
I just updated my packages as well as R and the problem is solved!
Thank you Thomas.
Fariba
