### ISSUE TITLE
tutorial 

### ISSUE THREAD

**Issue by MoMaz123** [tagteam/riskRegression#34]
Hi guys,  if  there is any  tutorial   for your  nice  PKG, thanks,

**Comment by tagteam** [comment]
depends on what you try to do (let me know!) ... there is a book ("Medical Risk Prediction Models: With Ties to Machine Learning") with chapter specific R-codes available here: https://github.com/tagteam/MedicalRiskPredictionModels. 
there is also an R-journal paper on the CSC function: 

Ozenne, et al. riskregression: Predicting the risk of an event using Cox regression models. R Journal, 9(2):440--460, 2017.

**Comment by MoMaz123** [comment]
Many thanks for the response, 
after running Cox LASOO I am having 10 variables (say, age, BMI, TG, TC, etc....) and want to make a risk score for them for my events variable (I have time as well), so it's survival. 
Your advice would be appreciated.

**Comment by MoMaz123** [comment]
Hi, any advise please.  thanks

**Comment by tagteam** [comment]
It is not clear how your question relates to riskRegression.

**Comment by MoMaz123** [comment]
Thanks, 
I want to make a risk prediction model or risk score using my 10 variables.

**Comment by tagteam** [comment]
Yes, this requires knowledge in addition to the software. There are many different ways to achieve the one or the other of your aims which depend heavily on the purpose of your research. It is not possible to advice you remotely, but please feel welcome to write about the background of your project in an email. This place here is solely for discussion problems with the software.
