### ISSUE TITLE
Is left truncation supported by the Score function?

### ISSUE THREAD

**Issue by NewUser36** [tagteam/riskRegression#35]
Hello,

I wanted to use the function Score in a survival analysis with left truncation and right censoring. The documentation of the function says "The function implements a toolbox for the risk prediction modeller: all tools work for the three outcomes: (1) binary (uncensored), (2) right censored time to event without competing risks, (3) right censored time to event with competing risks". When I try to use the function in R, I get a warning message saying the function does not handle left censoring. That being said, I haven't seen left truncation mentionned anywhere.

Is it safe to assume that this package handles left truncation?

Thanks!

**Comment by tagteam** [comment]
the Score function applies to prediction problems where at a well defined time zero a predicted probability is given to a subject (e.g., the probability of relapse or death within 5 years). Left truncation means that some individuals are not followed from time zero but enter at a later time point. So, your task is to define a proper prediction problem in your case with a well defined time zero at which you have predicted probabilities for all subjects in your test dataset. Once you have done that the Score function will probably work.
