### ISSUE TITLE
predictRisk for "GLMnet"

### ISSUE THREAD

**Issue by d-gomon** [tagteam/riskRegression#40]
Dear package maintainers,

To my great joy I saw that a few days ago a predictRisk method was written for the class `GLMnet`. I have had some problems when using this method though. Looking through the source code, I think I may have found some errors and oversight in the code. 

I am very unfamiliar with the procedure of raising issues on github, so please excuse me if I'm doing something wrong or if something is unclear. The problems I found were in the following files:

# `predictRisk.R`

* L1475: I think
`where <- sindex(jump.times=info$stop,eval.times=times)` 
should be
`where <- sindex(jump.times = sort(unique(info$stop)), eval.times = times)`
Otherwise you can go out of bounds as baseHaz_cpp in L1463 is ran with `predtimes = sort(unique(info$stop))`, meaning that when a model is built using non-unique event times an error will be returned. A simple example using an adjusted example from `predictRisk()`:

```{r}
# simulate learning and validation data
set.seed(10)
learndat <- sampleData(100,outcome="survival")
# We duplicate one of the entries to make stoptimes non-unique
learndat <- rbind(learndat, learndat[1,])
valdat <- sampleData(100,outcome="survival")

# Use GLMnet to predict survvival probabilities
fitGLMnet <- GLMnet(Surv(time,event)~X1+X8,data=learndat) ## Use CV as standard.
psurv <- predictRisk(fitGLMnet,newdata=valdat,times=seq(0,60,12))
> Error in cbind(0, 1 - coxnetSurv)[, 1 + where] : subscript out of bounds
```

# `fitters.R`

* L68: I believe `type.measure = "deviance"` should be` type.measure = type.measure` so users can specify their preferred measure type to `cv.glmnet()`.
* L65/68/77/80: It seems that `...` is missing in the arguments of `(cv.)glmnet()` calls, meaning users cannot specify their own arguments to `glmnet()` calls.
* L46: The description says that the elasticnet mixing parameter `alpha` is not used by cross-validation. I believe this is not true, the elasticnet parameter is normally passed to `glmnet()` from `cv.glmnet()` through the `...` argument. Not specifying it defaults to `alpha = 1`, meaning lasso regression is always performed (See the description of `cv.glmnet()`: "Note that cv.glmnet does NOT search for values for alpha. A specific value should be supplied, else alpha=1 is assumed by default."). 
The default value of `alpha = 1` is used in `GLMnet()`, however `alpha` is never fed to the `cv.glmnet()` functions in L68/80. 

My apologies if you were already aware of these issues, and thank you for your work on this package!

**Comment by jsohlendorff** [comment]
Thank you for your feedback. 

I have implemented your suggestions. Does that fix the problems that you were having?

**Comment by d-gomon** [comment]
Sorry for the late reply. Everything works as expected. Thank you very much!
