### ISSUE TITLE
Modified class of the `newdata` object

### ISSUE THREAD

**Issue by krzyzinskim** [tagteam/riskRegression#43]
Hi, thanks for a great package! 

I wonder why line 406 below is commented out. Because of this, the class of the `newdata` object is changed, which is rather unexpected behavior in some applications. Is it possible to uncomment this line? 

https://github.com/tagteam/riskRegression/blob/2679ad8a0f3aa043ac244050bf283df40e079b59/R/predictCox.R#L406-L407

**Comment by tagteam** [comment]
yes, just fixed on github. will push to CRAN in not so long. thanks for pointing this out.
