### ISSUE TITLE
Access the influence curve in Brier.survival / Brier.competing.risk / etc

### ISSUE THREAD

**Issue by anyafries** [tagteam/riskRegression#46]
Hi maintainers, thank you for a great package!

I am looking to use the influence curve estimates (i.e., iid decomposition of the scores) in an application along with other outputs from `Score`. Currently, this requires copying much of the package code. Would it be possible to add an additional option to the `keep` argument like `"if"` / `"influence"` / `"iid.decomp"` / similar which outputs the influence curve too?

It would be great to access it with something like`score$AUC$iid.decomp` (assumping `score` is the output from `Score()`).

In this case, adding the following lines to the files {AUC/Brier}.{survival/competing.risk}.R would enable us to access it:

``` r 
if (keep.iid) {
   output <- c(output,
      list(iid.decomp = DT[,c("ID","model","times","IF.Brier"), with=FALSE]))
}
```
changing IF.Brier to IF.AUC when needed and assuming that `keep.iid` is added in the "resolve keep statements" section of Score.R

Thanks very much!

**Comment by tagteam** [comment]
Yes, we could do that. But, what is your use case? we need to document that option somehow.

**Comment by anyafries** [comment]
My use case is to use these decompositions to estimate a covariance matrix for a multivariate version of the scores (i.e., for several time points). 

More generally, I think it lets users who are exploring the metrics in slightly more (theoretical) detail have easier access to this formulation to explore more open questions. Perhaps others may like to explore "which individuals contribute most greatly? which individuals make the scores more/less stable?" among other questions.

A more general documentation could be something like "_argument_name_ provides the centered i.i.d. decomposition of the scores, as described in Blanche (2015)."

Happy to provide more motivation if you'd like. Thanks again!

**Comment by tagteam** [comment]
right, thanks. I just pushed a new version with this new option. could you check if it works as expected?

**Comment by anyafries** [comment]
Thank you for such a quick update!

Brier works perfectly. AUC requires a small change which I also only realized this morning. The data table in the Brier Score files is called `DT` but is called `aucDT` in the AUC files. So, I think that the code in AUC.survival.R and AUC.competing.risks.R should actually be:

``` r
if (keep.iid[[1]] == TRUE && se.fit[[1]] == TRUE) {
            output <- c(output,
                        list(iid.decomp = aucDT[,data.table::data.table(ID,model,times,IF.AUC)]))
}
```

Thank you so much again!

**Comment by tagteam** [comment]
great catch. I just fixed this bug. does all work now? :)

**Comment by anyafries** [comment]
Yup, works perfectly. 
Thanks again!!
