### ISSUE TITLE
predict (and therefore plot) functions give strange results for objects of class "riskRegression"

### ISSUE THREAD

**Issue by drs81** [tagteam/riskRegression#47]
After fitting a riskRegression model, the predict (and therefore plot) functions dont appear to be working correctly. 

#Example
library(riskRegression)
library(prodlim)
data(Melanoma,package="riskRegression")
fit.arr <- ARR(Hist(time,status)~sex,data=Melanoma,cause=1)
fit.arr2 <- ARR(Hist(time,status)~sex + age,data=Melanoma,cause=1)

# slot $risk from the list object returned by predict functions gives a bunch of ones
predict(fit.arr,newdata=data.frame(sex=c("Female","Male")))
predict(fit.arr2,newdata=data.frame(sex=c("Female","Male"), age = c(60,60)))

#Example plot...

![strange plot from predict](https://github.com/tagteam/riskRegression/assets/93459413/a99379a9-d46e-43b7-91f3-ec1e09719d66)

**Comment by tagteam** [comment]
this was a bug related to a change between two alternative parametrizations that timereg::comp.risk allow (rcif vs rcif2). I just pushed a fix to github. hope this works now.

**Comment by drs81** [comment]
Great thanks for your prompt action Thomas.
