### ISSUE TITLE
riskRegression() and FGR() do not allow spline terms in model formula

### ISSUE THREAD

**Issue by drs81** [tagteam/riskRegression#48]
There seems to be a problem when one attempts to use a regression spline e.g. rms::rcs() or splines::ns() in the model formula for riskRegression() or FGR(). I am not sure if there is good reason for this and I'm missing something? It is allowed in a CSC() function, however. If it is a "valid" approach to fit a spline term, perhaps this feature can be allowed in future versions of riskRegression? I don't know how to do a feature request...I would be grateful if somebody can indicate how I do that.

**Comment by tagteam** [comment]
Yes, there is a good reason: riskRegression::riskRegression() is a wrapper with formula interface for timereg::comp.risk() and FGR is a wrapper with formula interface for cmprsk::crr(). Unfortunately, the spline options is not supported. But, if you can fix this I will happily include the patch :)

**Comment by drs81** [comment]
Hi Thomas,
Thank you for your reply. I can certainly try when I get some free time. I'm not sure how to go about this as I've never contributed to an R package source code. Can you please briefly advise?!

**Comment by tagteam** [comment]
Hi Daniel, well you clone or fork riskRegression from github and fix the problems (this will not be easy) and document the new features. when you are done, you can either email me the patch or use github's pull request feature.

**Comment by drs81** [comment]
Thanks for the information Thomas.
