### ISSUE TITLE
plotCalibration opens a graphic device even if plot = FALSE

### ISSUE THREAD

**Issue by erikvona** [tagteam/riskRegression#49]
Hi,

I'm using riskRegression in a shiny app, and due to a very specific set of circumstances, opening up a graphics device with default settings is a problem.
I'm using `plotCalibration` with `plot = FALSE` to create a data frame that I will process further. However, this opens up a graphics device if none is open.

You can verify this by using the following code:

``` r
library(riskRegression)
#> riskRegression version 2023.03.22
library(survival)
data(Melanoma)
f1 <- CSC(Hist(time,status)~age+sex+epicel+ulcer,data=Melanoma)
x <- Score(list(model1=f1),Hist(time,status)~1,data=Melanoma,
           cause= 2,times=5*365.25,plots="cal")
if(!is.null(dev.list())) dev.off()
#> null device 
#>           1
dev.list()
#> NULL
x2 <- plotCalibration(x, plot = FALSE)
#> The default method for estimating calibration curves based on censored data has changed for riskRegression version 2019-9-8 or higher
#> Set cens.method="jackknife" to get the estimate using pseudo-values.
#> However, note that the option "jackknife" is sensititve to violations of the assumption that the censoring is independent of both the event times and the covariates.
#> Set cens.method="local" to suppress this message.
dev.list()
#> pdf 
#>   2
```

<sup>Created on 2023-11-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I've tracked this down to the following line: 
[cex.lab=par()$cex.lab,](https://github.com/tagteam/riskRegression/blob/bf236853f363637b22835c10067237069f7b185b/R/plotCalibration.R#L349C48-L349C48).
The call to `par()` opens up a graphics device if none is open, and that line is run regardless of whether a plot will be produced.

Would it be possible to move this section a little bit down, inside the `if (bars){`? As far as I can tell that won't affect functionality, except the device won't be opened if `bars` is `FALSE`, and that way I can avoid the device being opened.

If not, no harm, I've got a workaround by opening up a specific graphics device prior to calling `plotCalibration`, but that's a strange thing to do.

Thanks again for the excellent package!

**Comment by tagteam** [comment]
I have just moved the par() statements into the if (bars) section. :) let me know if this solves your issue.

**Comment by erikvona** [comment]
Thank you very much! I've verified that this solves my issue!
