### ISSUE TITLE
plotBrier only displays last model

### ISSUE THREAD

**Issue by jwilliman** [tagteam/riskRegression#5]
Hello.

When running the example code from `plotBrier` I can only see the one of the three lines that should be displayed in the plot. I'm not smart enough to figure out from the code where the problem is.

``` r

library(riskRegression)
#> riskRegression version 2020.02.05
library(survival)

ds1=sampleData(40,outcome="survival")
ds2=sampleData(40,outcome="survival")
f1 <- coxph(Surv(time,event)~X1+X3+X5+X7+X9,data=ds1,x=TRUE)
f2 <- coxph(Surv(time,event)~X2+X4+X6+X8+X10,data=ds1,x=TRUE)
xscore <- Score(list(f1,f2),formula=Hist(time,event)~1,data=ds2,times=0:12,metrics="brier")
plotBrier(xscore)
```

![](https://i.imgur.com/DuR3uFO.png)

<sup>Created on 2020-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks very much.

Jonathan

**Comment by tagteam** [comment]
sorry, I cannot reproduce this. Could this be related to the plotting device in R-studio on a mac? Can you see all three curves when you use a pdf device:
pdf("test-plot.pdf")
plotBrier(xscore)
dev.off()

**Comment by jwilliman** [comment]
Thank you. 

You are correct this does appear to be an R-studio related issue, although I'm running windows rather than on a Mac.  I can see all three lines when I run the code directly through R, or as you suggested when saved as a pdf. I've provided my sessionInfo below. Perhaps I should follow this up directly with RStudio?

```{r}

> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252   
[3] LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                        
[5] LC_TIME=English_New Zealand.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] survival_3.1-8            riskRegression_2020.02.05

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3          mvtnorm_1.0-12      lattice_0.20-38     png_0.1-7           zoo_1.8-7          
 [6] assertthat_0.2.1    digest_0.6.23       foreach_1.4.7       R6_2.4.1            backports_1.1.5    
[11] acepack_1.4.1       MatrixModels_0.4-1  ggplot2_3.2.1       pillar_1.4.3        rlang_0.4.4        
[16] lazyeval_0.2.2      multcomp_1.4-12     rstudioapi_0.10     data.table_1.12.8   SparseM_1.78       
[21] rpart_4.1-15        Matrix_1.2-18       checkmate_1.9.4     splines_3.6.2       stringr_1.4.0      
[26] foreign_0.8-75      htmlwidgets_1.5.1   munsell_0.5.0       numDeriv_2016.8-1.1 compiler_3.6.2     
[31] xfun_0.12           pkgconfig_2.0.3     base64enc_0.1-3     htmltools_0.4.0     nnet_7.3-12        
[36] tidyselect_1.0.0    tibble_2.1.3        gridExtra_2.3       htmlTable_1.13.3    prodlim_2019.11.13 
[41] Hmisc_4.3-0         rms_5.1-4           codetools_0.2-16    crayon_1.3.4        dplyr_0.8.4        
[46] MASS_7.3-51.5       timereg_1.9.4       grid_3.6.2          nlme_3.1-143        polspline_1.1.17   
[51] gtable_0.3.0        lifecycle_0.1.0     magrittr_1.5        scales_1.1.0        stringi_1.4.5      
[56] latticeExtra_0.6-29 sandwich_2.5-1      Formula_1.2-3       TH.data_1.0-10      lava_1.6.6         
[61] RColorBrewer_1.1-2  iterators_1.0.12    tools_3.6.2         cmprsk_2.2-9        glue_1.3.1         
[66] purrr_0.3.3         jpeg_0.1-8.1        colorspace_1.4-1    cluster_2.1.0       knitr_1.27         
[71] quantreg_5.5


> RStudio.Version()
$citation

To cite RStudio in publications use:

  RStudio Team (2019). RStudio:
  Integrated Development for R. RStudio,
  Inc., Boston, MA URL
  http://www.rstudio.com/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{RStudio Team}},
    organization = {RStudio, Inc.},
    address = {Boston, MA},
    year = {2019},
    url = {http://www.rstudio.com/},
  }


$mode
[1] "desktop"

$version
[1] ‘1.2.5001’
```

**Comment by tagteam** [comment]
good. yes, try ask them and if they have a useful answer please share
with me :)

cheers

jwilliman <notifications@github.com> writes:

> Thank you. 
>
> You are correct this does appear to be an R-studio related issue,
> although I'm running windows rather than on a Mac.  I can see all
> three lines when I run the code directly through R, or as you
> suggested when saved as a pdf. I've provided my sessionInfo
> below. Perhaps I should follow this up directly with RStudio?
>
> ```{r}
>
>> sessionInfo()
> R version 3.6.2 (2019-12-12)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 17134)
>
> Matrix products: default
>
> locale:
> [1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252   
> [3] LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                        
> [5] LC_TIME=English_New Zealand.1252    
>
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
>
> other attached packages:
> [1] survival_3.1-8            riskRegression_2020.02.05
>
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.3          mvtnorm_1.0-12      lattice_0.20-38     png_0.1-7           zoo_1.8-7          
>  [6] assertthat_0.2.1    digest_0.6.23       foreach_1.4.7       R6_2.4.1            backports_1.1.5    
> [11] acepack_1.4.1       MatrixModels_0.4-1  ggplot2_3.2.1       pillar_1.4.3        rlang_0.4.4        
> [16] lazyeval_0.2.2      multcomp_1.4-12     rstudioapi_0.10     data.table_1.12.8   SparseM_1.78       
> [21] rpart_4.1-15        Matrix_1.2-18       checkmate_1.9.4     splines_3.6.2       stringr_1.4.0      
> [26] foreign_0.8-75      htmlwidgets_1.5.1   munsell_0.5.0       numDeriv_2016.8-1.1 compiler_3.6.2     
> [31] xfun_0.12           pkgconfig_2.0.3     base64enc_0.1-3     htmltools_0.4.0     nnet_7.3-12        
> [36] tidyselect_1.0.0    tibble_2.1.3        gridExtra_2.3       htmlTable_1.13.3    prodlim_2019.11.13 
> [41] Hmisc_4.3-0         rms_5.1-4           codetools_0.2-16    crayon_1.3.4        dplyr_0.8.4        
> [46] MASS_7.3-51.5       timereg_1.9.4       grid_3.6.2          nlme_3.1-143        polspline_1.1.17   
> [51] gtable_0.3.0        lifecycle_0.1.0     magrittr_1.5        scales_1.1.0        stringi_1.4.5      
> [56] latticeExtra_0.6-29 sandwich_2.5-1      Formula_1.2-3       TH.data_1.0-10      lava_1.6.6         
> [61] RColorBrewer_1.1-2  iterators_1.0.12    tools_3.6.2         cmprsk_2.2-9        glue_1.3.1         
> [66] purrr_0.3.3         jpeg_0.1-8.1        colorspace_1.4-1    cluster_2.1.0       knitr_1.27         
> [71] quantreg_5.5
>
>
>> RStudio.Version()
> $citation
>
> To cite RStudio in publications use:
>
>   RStudio Team (2019). RStudio:
>   Integrated Development for R. RStudio,
>   Inc., Boston, MA URL
>   http://www.rstudio.com/.
>
> A BibTeX entry for LaTeX users is
>
>   @Manual{,
>     title = {RStudio: Integrated Development Environment for R},
>     author = {{RStudio Team}},
>     organization = {RStudio, Inc.},
>     address = {Boston, MA},
>     year = {2019},
>     url = {http://www.rstudio.com/},
>   }
>
>
> $mode
> [1] "desktop"
>
> $version
> [1] ‘1.2.5001’
> ```

-- 
7LL-1 Make peace with your past so it doesn’t spoil your present.
