### ISSUE TITLE
Issue with predictRisk.coxph.penal

### ISSUE THREAD

**Issue by RobinDenz1** [tagteam/riskRegression#50]
Sorry to bother you again, but I think I have found a bug in the `predictRisk.coxph.penal` function.

Below is a small reproducible example that shows the problem:

```R
library(riskRegression)
library(survival)

set.seed(245)

data(nafld, package="survival")

# generating random cluster
nafld1$clust <- sample(1:10, size=nrow(nafld1), replace=TRUE)
nafld1$cluster <- nafld1$clust

# fitting a model with a frailty term without naming it "cluster"
model1 <- coxph(Surv(futime, status) ~ age + male + frailty(clust),
               data=nafld1, x=TRUE)

# fitting a model with a frailty term named "cluster"
model2 <- coxph(Surv(futime, status) ~ age + male + frailty(cluster),
               data=nafld1, x=TRUE)

# getting predictions
test1 <- predictRisk(model1, nafld1, times=100)
test2 <- predictRisk(model2, nafld1, times=100) 

all.equal(test[,1], test2)
```

The output of the function seems to depent on whether or not the variable inside the `frailty()` term is called "cluster" or not. A peek into the source code revealed to me that this is due to line 756-757 in predictRisk.r. The if statement checks whethere the history is empty and simply calls the standard `predictRisk.coxph` method if so. The problem is that if the user named their cluster anything but "cluster", this will not be picked up by `object$history$'frailty(cluster)'$history`. For instance, if the cluster is named "clust", the correct lookup would be `object$history$'frailty(clust)'$history`.

 Since only one frailty term is allowed anyways I think a simple solution to the issue would be to replace line 756 with `frailhistory <- object$history[[1]]$history`.

Thanks for the excellent package and your time.

**Comment by tagteam** [comment]
thank you for finding this bug. I just pushed a fix to github and submit
to CRAN later this week

Robin Denz ***@***.***> writes:

> Sorry to bother you again, but I think I have found a bug in the `predictRisk.coxph.penal` function.
>
> Below is a small reproducible example that shows the problem:
>
> ```R
> library(riskRegression)
> library(survival)
>
> set.seed(245)
>
> data(nafld, package="survival")
>
> # generating random cluster
> nafld1$clust <- sample(1:10, size=nrow(nafld1), replace=TRUE)
> nafld1$cluster <- nafld1$clust
>
> # fitting a model with a frailty term without naming it "cluster"
> model1 <- coxph(Surv(futime, status) ~ age + male + frailty(clust),
>                data=nafld1, x=TRUE)
>
> # fitting a model with a frailty term named "cluster"
> model2 <- coxph(Surv(futime, status) ~ age + male + frailty(cluster),
>                data=nafld1, x=TRUE)
>
> # getting predictions
> test1 <- predictRisk(model1, nafld1, times=100)
> test2 <- predictRisk(model2, nafld1, times=100) 
>
> all.equal(test[,1], test2)
> ```
>
> The output of the function seems to depent on whether or not the variable inside the `frailty()` term is called "cluster" or not. A peek into the source code revealed to me that this is due to line 756-757 in predictRisk.r. The if statement checks whethere the history is empty and simply calls the standard `predictRisk.coxph` method if so. The problem is that if the user named their cluster anything but "cluster", this will not be picked up by `object$history$'frailty(cluster)'$history`. For instance, if the cluster is named "clust", the correct lookup would be `object$history$'frailty(clust)'$history`.
>
>  Since only one frailty term is allowed anyways I think a simple solution to the issue would be to replace line 756 with `frailhistory <- object$history[[1]]$history`.
>
> Thanks for the excellent package and your time.

-- 
7LL-6 Stop thinking too much, it’s alright not to know all the answers.
