### ISSUE TITLE
Score function reports error

### ISSUE THREAD

**Issue by zhangkaicr** [tagteam/riskRegression#51]
[DATA(1).zip](https://github.com/tagteam/riskRegression/files/13961148/DATA.1.zip)

Thank you very much for developing this R package. I now hope to use this package to construct the cox regression equation and calculate the AUC value, but I don’t know why I always get an error. I will now send you the test data. I would be very grateful if you could help find out the cause of the error. I don't know if it's a problem with the package or with my data itself.

`
library(riskRegression)
library(tidyverse)
library(survival)

load("DATA(1).Rdata")

# 建立 COX 回归模型
cox_model <- coxph(Surv(day,mort)~age+SOFA+ALP,data=data_train,x=1)
# 查看回归系数
cox_model |> 
  broom::tidy()

auc_train <- 
  Score(list(cox_model), debug = F,
        formula=Surv(day,mort)~1,
        data=data_train, 
        metrics="auc", 
        null.model=FALSE)

plotAUC(auc_train,conf.int=TRUE)
`

**Comment by tagteam** [comment]
thank you for pointing this out. the reason for the data.table related bug was that you have a variable N in the data and the Score function uses a variable N. before we used data[,ID:=1:N] which in your case used the N from the data . I just pushed a patch to github where now data[["ID"]]=1:N works also in your case. by the way, in addition to broom you may want to look at cox_model |> Publish::publish()
