### ISSUE TITLE
Assess differences in Brier Scores

### ISSUE THREAD

**Issue by Selenia94** [tagteam/riskRegression#53]
Thank you for the great package !

It is certainly an open question, but I'm wondering if there is a relevant way to assess whether the predictive performances of two different risk prediction models (let's say, the Brier Scores obtained from two Cox models) are "statistically" different. 
More generally, the idea would be to determine whether it is possible to establish a threshold beyond which the magnitude of the difference between these Brier scores would be considered significant.

Thanks a lot !

**Comment by tagteam** [comment]
hmm, the package does provide statistical significance tests for the
Brier scores of two Cox models based on
external test data, or crossvalidation. e.g.,

library(riskRegression)
library(survival)
set.seed(8)
learn=sampleData(337,outcome="survival")
test=sampleData(419,outcome="survival")
cox1=coxph(Surv(time,event)~X1+X8,data=learn,x=TRUE)
cox2=coxph(Surv(time,event)~X2+X3+X4+X5+X6,data=learn,x=TRUE)
x=Score(list(cox1=cox1,cox2=cox2),data=test,Surv(time,event)~1,metrics="Brier",times=5)
Results of model comparisons:

   times model  reference delta.Brier lower upper              p
1:     5  cox1 Null model        -1.2  -2.4  -0.0 0.044672793727
2:     5  cox2 Null model        -4.9  -7.0  -2.9 0.000003081766
3:     5  cox2       cox1        -3.7  -6.2  -1.2 0.003415800741

maybe you are asking about the subject-matter significance of the
models? this would require quantifiable knowlegde about whatever intervention/action
should be based on the predicted risk and the subsequent costs/benefits.



Selenia94 ***@***.***> writes:

> Thank you for the great package !
>
> It is certainly an open question, but I'm wondering if there is a
> relevant way to assess whether the predictive performances of two
> different risk prediction models (let's say, the Brier Scores obtained
> from two Cox models) are "statistically" different.
> More generally, the idea would be to determine whether it is possible
> to establish a threshold beyond which the magnitude of the difference
> between these Brier scores would be considered significant.
>
> Thanks a lot ! 

-- 
7LL-6 Stop thinking too much, it’s alright not to know all the answers.
