### ISSUE TITLE
Integrated Brier Score - error

### ISSUE THREAD

**Issue by DzenisKoca** [tagteam/riskRegression#54]
Hello,

While trying to calculate the IBS for in-house dataset, using the score function, I got the following error:
>"Error in getPerformanceData(testdata = data, testweights = Weights, traindata = NULL,  : 
Missing values in predicted risk detected."

While debugging, I have also tried to reproduce the example given in the description of score() function, and it returned the same error.

Example: 
```library(rms)
library(prodlim)
set.seed(18)
trainSurv <- sampleData(100,outcome="survival")
testSurv <- sampleData(40,outcome="survival")
cox1 = coxph(Surv(time,event)~X1+X2+X7+X9,data=trainSurv, y=TRUE, x = TRUE)
cox2 = coxph(Surv(time,event)~X3+X5+X6,data=trainSurv, y=TRUE, x = TRUE)
## End(Not run)
# Integrated Brier score
## Not run: 
xs=Score(list("Cox(X1+X2+X7+X9)"=cox1,"Cox(X3+X5+X6)"=cox2),
         formula=Surv(time,event)~1,data=testSurv,conf.int=FALSE,
         summary="ibs",
         times=sort(unique(testSurv$time)))
```

> "Error in getPerformanceData(testdata = data, testweights = Weights, traindata = NULL,  : 
Missing values in predicted risk detected."

What I have realized is that testSurv$time has values that are larger than highest time of trainSurv$time, and it seems that score function gives error in this case. 
```
`max(testSurv$time) > max(trainSurv$time)
```
> [1] TRUE

Is my observation right, and can I proceed by limiting the times argument such that unique survival times of test data are not larger than ones in train data? 
For example: 
```
times=sort(unique(testSurv$time[testSurv$time < trainSurv$time]))
```

**Comment by tagteam** [comment]
Hi

I agree that the error is confusing in this case. but the problem is
really that there are missing values in the predicted risks. as you have
already guessed this has to do with the time points in the test dataset
which are beyond the maximal time point in the learning dataset. the
Breslow estimate of the baseline hazard function in the Cox model does
not extrapolate, hence the missing values:

```
predictRisk(cox1,testSurv,times=sort(unique(testSurv$time)))
predictRisk(cox2,testSurv,times=sort(unique(testSurv$time)))
```
you can get rid of the problem by shortening the times vector, e.g.,

``` sort(unique(testSurv$time))[1:36] ```

in my experience it is usually necessary to be less ambitious with
predicted risks for large time horizons.

best Thomas



DzenisKoca ***@***.***> writes:

> Hello,
>
> While trying to calculate the IBS for in-house dataset, using the score function, I got the following error:
>>"Error in getPerformanceData(testdata = data, testweights = Weights, traindata = NULL,  : 
> Missing values in predicted risk detected."
>
> While debugging, I have also tried to reproduce the example given in
> the description of score() function, and it returned the same error.
>
> Example: 
> ```library(rms)
> library(prodlim)
> set.seed(18)
> trainSurv <- sampleData(100,outcome="survival")
> testSurv <- sampleData(40,outcome="survival")
> cox1 = coxph(Surv(time,event)~X1+X2+X7+X9,data=trainSurv, y=TRUE, x = TRUE)
> cox2 = coxph(Surv(time,event)~X3+X5+X6,data=trainSurv, y=TRUE, x = TRUE)
> ## End(Not run)
> # Integrated Brier score
> ## Not run: 
> xs=Score(list("Cox(X1+X2+X7+X9)"=cox1,"Cox(X3+X5+X6)"=cox2),
>          formula=Surv(time,event)~1,data=testSurv,conf.int=FALSE,
>          summary="ibs",
>          times=sort(unique(testSurv$time)))
> ```
>
>> "Error in getPerformanceData(testdata = data, testweights = Weights, traindata = NULL,  : 
> Missing values in predicted risk detected."
>
>
> What I have realized is that testSurv$time has values that are larger
> than highest time of trainSurv$time, and it seems that score function
> gives error in this case.
> ```
> `max(testSurv$time) > max(trainSurv$time)
> ```
>> [1] TRUE
>
> Is my observation right, and can I proceed by limiting the times
> argument such that unique survival times of test data are not larger
> than ones in train data?
> For example: 
> ```
> times=sort(unique(testSurv$time[testSurv$time < trainSurv$time]))
> ```

-- 
7LL-6 Stop thinking too much, it’s alright not to know all the answers.
