### ISSUE TITLE
Weighted Competing Risks Models

### ISSUE THREAD

**Issue by Jeanselme** [tagteam/riskRegression#55]
Hello,

Would there be a way to fit a weighted competing risk model (either FineGray or CSCox) and predict with this model. I believe, one can currently fit the CSCox with weights but not predict with it.

Thanks for your help

**Comment by tagteam** [comment]
Hi, it is unclear which equations you have in mind. could you provide a reference (with the formula) for what you try to achieve? If you want to estimate an average treatment effect by combining a propensity score model with the prediction of risks, then you could have a look at the function riskRegression:ate()

**Comment by Jeanselme** [comment]
Thank you for your quick response, my intersest is to predict risk under both treatment regimes for new datapoints. I would like to obtain the CIF under both regimes with a weighted baseline (I was thinking adapting the adapted Breslow proposed in the [original Fine Gray paper](https://www.jstor.org/stable/2670170?seq=4) just before Eq (8))

**Comment by tagteam** [comment]
I see, this is still rather vague and certainly not implemented in riskRegression :)
