### ISSUE TITLE
Time-varying AUC vs {risksetROC} package

### ISSUE THREAD

**Issue by ellessenne** [tagteam/riskRegression#56]
Hi,

I was trying to implement the [integrated AUC](https://pubmed.ncbi.nlm.nih.gov/15737082/) as an "overall" summary measure of time-varying AUC for survival outcomes, and came across the {risksetROC} package which seems to implement it. Side note: is this something that {riskRegression} can already calculate?

After fiddling around with it, I noticed that it estimates time-varying AUC values that are very different compared to what reported by the `Score()` function from {riskRegression}, see e.g. the following example:

``` r
library(reprex)
library(rstpm2)
#> Loading required package: survival
#> Loading required package: splines
#> 
#> Attaching package: 'rstpm2'
#> The following object is masked from 'package:survival':
#> 
#>     colon
library(riskRegression)
#> riskRegression version 2023.12.21
library(risksetROC)
#> Loading required package: MASS
library(survival)
library(devtools)
#> Loading required package: usethis

data(brcancer)
mod <- coxph(
  Surv(rectime, censrec == 1) ~ hormon + x1 + x2 + x3 + x4 + x5 + x6 + x7,
  data = brcancer,
  x = TRUE,
  y = TRUE)

CoxWeights(
  marker = mod$linear.predictors,
  Stime = brcancer$rectime,
  status = brcancer$censrec,
  predict.time = 300
)$AUC
#> [1] 0.659743

Score(
  list(mod),
  formula = update(mod$formula, . ~ 1),
  data = brcancer,
  times = 300,
  metrics = "auc"
)
#> 
#> Metric AUC:
#> 
#> Results by model:
#> 
#>     model times    AUC  lower  upper
#>    <fctr> <num> <char> <char> <char>
#> 1:  coxph   300   74.1   66.4   81.9
#> 
#> NOTE: Values are multiplied by 100 and given in %.
#> NOTE: The higher AUC the better.
```

`CoxWeights()` from the {risksetROC} package reports an AUC of 0.659 at 300 days, while `Score()` from the {riskRegression} package reports an AUC of 0.741. Am I missing something here? Or are these two not referring to the same AUC?

Many thanks in advance,

Alessandro

P.s., R session info:

``` r
session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.3 (2024-02-29)
#>  os       macOS Sonoma 14.4.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Europe/Stockholm
#>  date     2024-04-15
#>  pandoc   3.1.1 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package        * version    date (UTC) lib source
#>  backports        1.4.1      2021-12-13 [1] CRAN (R 4.3.0)
#>  base64enc        0.1-3      2015-07-28 [1] CRAN (R 4.3.0)
#>  bbmle            1.0.25.1   2023-12-09 [1] CRAN (R 4.3.2)
#>  bdsmatrix        1.3-7      2024-03-02 [1] CRAN (R 4.3.3)
#>  cachem           1.0.8      2023-05-01 [1] CRAN (R 4.3.0)
#>  checkmate        2.3.1      2023-12-04 [1] CRAN (R 4.3.1)
#>  cli              3.6.2      2023-12-11 [1] CRAN (R 4.3.2)
#>  cluster          2.1.6      2023-12-01 [2] CRAN (R 4.3.3)
#>  cmprsk           2.2-11     2022-01-06 [1] CRAN (R 4.3.0)
#>  codetools        0.2-20     2024-03-31 [2] CRAN (R 4.3.3)
#>  colorspace       2.1-0      2023-01-23 [1] CRAN (R 4.3.0)
#>  data.table       1.15.4     2024-03-30 [1] CRAN (R 4.3.3)
#>  deSolve          1.40       2023-11-27 [1] CRAN (R 4.3.2)
#>  devtools       * 2.4.5      2022-10-11 [1] CRAN (R 4.3.0)
#>  digest           0.6.35     2024-03-11 [1] CRAN (R 4.3.3)
#>  dplyr            1.1.4      2023-11-17 [1] CRAN (R 4.3.1)
#>  ellipsis         0.3.2      2021-04-29 [1] CRAN (R 4.3.0)
#>  evaluate         0.23       2023-11-01 [1] CRAN (R 4.3.1)
#>  fansi            1.0.6      2023-12-08 [1] CRAN (R 4.3.2)
#>  fastmap          1.1.1      2023-02-24 [1] CRAN (R 4.3.0)
#>  foreach          1.5.2      2022-02-02 [1] CRAN (R 4.3.0)
#>  foreign          0.8-86     2023-11-28 [2] CRAN (R 4.3.3)
#>  Formula          1.2-5      2023-02-24 [1] CRAN (R 4.3.0)
#>  fs               1.6.3      2023-07-20 [1] CRAN (R 4.3.0)
#>  future           1.33.2     2024-03-26 [1] CRAN (R 4.3.3)
#>  future.apply     1.11.2     2024-03-28 [1] CRAN (R 4.3.3)
#>  generics         0.1.3      2022-07-05 [1] CRAN (R 4.3.0)
#>  ggplot2          3.5.0      2024-02-23 [1] CRAN (R 4.3.1)
#>  globals          0.16.3     2024-03-08 [1] CRAN (R 4.3.3)
#>  glue             1.7.0      2024-01-09 [1] CRAN (R 4.3.1)
#>  gridExtra        2.3        2017-09-09 [1] CRAN (R 4.3.0)
#>  gtable           0.3.4      2023-08-21 [1] CRAN (R 4.3.1)
#>  Hmisc            5.1-2      2024-03-11 [1] CRAN (R 4.3.3)
#>  htmlTable        2.4.2      2023-10-29 [1] CRAN (R 4.3.1)
#>  htmltools        0.5.8.1    2024-04-04 [1] CRAN (R 4.3.1)
#>  htmlwidgets      1.6.4      2023-12-06 [1] CRAN (R 4.3.2)
#>  httpuv           1.6.15     2024-03-26 [1] CRAN (R 4.3.3)
#>  iterators        1.0.14     2022-02-05 [1] CRAN (R 4.3.0)
#>  knitr            1.46       2024-04-06 [1] CRAN (R 4.3.3)
#>  later            1.3.2      2023-12-06 [1] CRAN (R 4.3.1)
#>  lattice          0.22-6     2024-03-20 [2] CRAN (R 4.3.3)
#>  lava             1.8.0      2024-03-05 [1] CRAN (R 4.3.3)
#>  lifecycle        1.0.4      2023-11-07 [1] CRAN (R 4.3.2)
#>  listenv          0.9.1      2024-01-29 [1] CRAN (R 4.3.1)
#>  magrittr         2.0.3      2022-03-30 [1] CRAN (R 4.3.0)
#>  MASS           * 7.3-60.0.1 2024-01-13 [2] CRAN (R 4.3.3)
#>  Matrix           1.6-5      2024-01-11 [1] CRAN (R 4.3.2)
#>  MatrixModels     0.5-3      2023-11-06 [1] CRAN (R 4.3.2)
#>  memoise          2.0.1      2021-11-26 [1] CRAN (R 4.3.0)
#>  mets             1.3.4      2024-02-16 [1] CRAN (R 4.3.1)
#>  mgcv             1.9-1      2023-12-21 [2] CRAN (R 4.3.3)
#>  mime             0.12       2021-09-28 [1] CRAN (R 4.3.0)
#>  miniUI           0.1.1.1    2018-05-18 [1] CRAN (R 4.3.0)
#>  multcomp         1.4-25     2023-06-20 [1] CRAN (R 4.3.0)
#>  munsell          0.5.1      2024-04-01 [1] CRAN (R 4.3.3)
#>  mvtnorm          1.2-4      2023-11-27 [1] CRAN (R 4.3.2)
#>  nlme             3.1-164    2023-11-27 [2] CRAN (R 4.3.3)
#>  nnet             7.3-19     2023-05-03 [2] CRAN (R 4.3.3)
#>  numDeriv         2016.8-1.1 2019-06-06 [1] CRAN (R 4.3.0)
#>  parallelly       1.37.1     2024-02-29 [1] CRAN (R 4.3.2)
#>  pillar           1.9.0      2023-03-22 [1] CRAN (R 4.3.0)
#>  pkgbuild         1.4.4      2024-03-17 [1] CRAN (R 4.3.3)
#>  pkgconfig        2.0.3      2019-09-22 [1] CRAN (R 4.3.0)
#>  pkgload          1.3.4      2024-01-16 [1] CRAN (R 4.3.1)
#>  polspline        1.1.24     2023-10-26 [1] CRAN (R 4.3.1)
#>  prodlim          2023.08.28 2023-08-28 [1] CRAN (R 4.3.1)
#>  profvis          0.3.8      2023-05-02 [1] CRAN (R 4.3.0)
#>  promises         1.3.0      2024-04-05 [1] CRAN (R 4.3.1)
#>  purrr            1.0.2      2023-08-10 [1] CRAN (R 4.3.1)
#>  quantreg         5.97       2023-08-19 [1] CRAN (R 4.3.1)
#>  R.cache          0.16.0     2022-07-21 [1] CRAN (R 4.3.0)
#>  R.methodsS3      1.8.2      2022-06-13 [1] CRAN (R 4.3.0)
#>  R.oo             1.26.0     2024-01-24 [1] CRAN (R 4.3.1)
#>  R.utils          2.12.3     2023-11-18 [1] CRAN (R 4.3.1)
#>  R6               2.5.1      2021-08-19 [1] CRAN (R 4.3.0)
#>  Rcpp             1.0.12     2024-01-09 [1] CRAN (R 4.3.2)
#>  remotes          2.5.0      2024-03-17 [1] CRAN (R 4.3.3)
#>  reprex         * 2.1.0      2024-01-11 [1] CRAN (R 4.3.1)
#>  riskRegression * 2023.12.21 2023-12-19 [1] CRAN (R 4.3.1)
#>  risksetROC     * 1.0.4.1    2022-06-13 [1] CRAN (R 4.3.0)
#>  rlang            1.1.3      2024-01-10 [1] CRAN (R 4.3.1)
#>  rmarkdown        2.26       2024-03-05 [1] CRAN (R 4.3.3)
#>  rms              6.8-0      2024-03-11 [1] CRAN (R 4.3.3)
#>  rpart            4.1.23     2023-12-05 [2] CRAN (R 4.3.3)
#>  rstpm2         * 1.6.3      2023-12-05 [1] CRAN (R 4.3.1)
#>  rstudioapi       0.16.0     2024-03-24 [1] CRAN (R 4.3.3)
#>  sandwich         3.1-0      2023-12-11 [1] CRAN (R 4.3.2)
#>  scales           1.3.0      2023-11-28 [1] CRAN (R 4.3.1)
#>  sessioninfo      1.2.2      2021-12-06 [1] CRAN (R 4.3.0)
#>  shiny            1.8.1.1    2024-04-02 [1] CRAN (R 4.3.3)
#>  SparseM          1.81       2021-02-18 [1] CRAN (R 4.3.0)
#>  stringi          1.8.3      2023-12-11 [1] CRAN (R 4.3.1)
#>  stringr          1.5.1      2023-11-14 [1] CRAN (R 4.3.2)
#>  styler           1.10.3     2024-04-07 [1] CRAN (R 4.3.1)
#>  survival       * 3.5-8      2024-02-14 [2] CRAN (R 4.3.3)
#>  TH.data          1.1-2      2023-04-17 [1] CRAN (R 4.3.0)
#>  tibble           3.2.1      2023-03-20 [1] CRAN (R 4.3.0)
#>  tidyselect       1.2.1      2024-03-11 [1] CRAN (R 4.3.3)
#>  timereg          2.0.5      2023-01-17 [1] CRAN (R 4.3.0)
#>  urlchecker       1.0.1      2021-11-30 [1] CRAN (R 4.3.0)
#>  usethis        * 2.2.3      2024-02-19 [1] CRAN (R 4.3.1)
#>  utf8             1.2.4      2023-10-22 [1] CRAN (R 4.3.1)
#>  vctrs            0.6.5      2023-12-01 [1] CRAN (R 4.3.1)
#>  withr            3.0.0      2024-01-16 [1] CRAN (R 4.3.1)
#>  xfun             0.43       2024-03-25 [1] CRAN (R 4.3.3)
#>  xtable           1.8-4      2019-04-21 [1] CRAN (R 4.3.0)
#>  yaml             2.3.8      2023-12-11 [1] CRAN (R 4.3.1)
#>  zoo              1.8-12     2023-04-13 [1] CRAN (R 4.3.0)
#> 
#>  [1] /Users/alessandro.gasparini/R-lib
#>  [2] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

<sup>Created on 2024-04-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ellessenne** [comment]
I also added a comparison with the {survivalROC} package, which computes different values to both {riskRegression} and {risksetROC}:

``` r
library(rstpm2)
#> Loading required package: survival
#> Loading required package: splines
#> 
#> Attaching package: 'rstpm2'
#> The following object is masked from 'package:survival':
#> 
#>     colon
library(riskRegression)
#> riskRegression version 2023.12.21
library(risksetROC)
#> Loading required package: MASS
library(survival)
library(devtools)
#> Loading required package: usethis
library(tidyverse)
library(survivalROC)

data(brcancer)
mod <- coxph(
  Surv(rectime, censrec == 1) ~ hormon + x1 + x2 + x3 + x4 + x5 + x6 + x7,
  data = brcancer,
  x = TRUE,
  y = TRUE
)

times <- unique(brcancer$rectime[brcancer$censrec == 1])

AUC_risksetROC <- map_dbl(.x = times, .f = function(t) {
  CoxWeights(
    marker = mod$linear.predictors,
    Stime = brcancer$rectime,
    status = brcancer$censrec,
    predict.time = t
  )$AUC
})

AUC_survivalROC <- map_dbl(.x = times, .f = function(t) {
  survivalROC(
    marker = mod$linear.predictors,
    Stime = brcancer$rectime,
    status = brcancer$censrec,
    predict.time = t,
    method = "KM"
  )$AUC
})

AUC_riskRegression <- Score(
  list(mod),
  formula = update(mod$formula, . ~ 1),
  data = brcancer,
  times = times,
  metrics = "auc"
)$AUC$score$AUC

St <- survfit(formula = update(mod$formula, . ~ 1), data = brcancer)
St <- summary(St, times = times)$surv

dt <- bind_rows(
  data.frame(times, St, AUC = AUC_riskRegression, method = "{riskRegression}"),
  data.frame(times, St, AUC = AUC_survivalROC, method = "{survivalROC}"),
  data.frame(times, St, AUC = AUC_risksetROC, method = "{risksetROC}")
)

ggplot(dt, aes(x = times, y = AUC, color = method)) +
  geom_line()
```

![](https://i.imgur.com/SkMYMa8.png)

``` r

with(filter(dt, method == "{riskRegression}"), IntegrateAUC(AUC = AUC, utimes = times, St = St, tmax = max(times)))
#> [1] 0.7491338
with(filter(dt, method == "{survivalROC}"), IntegrateAUC(AUC = AUC, utimes = times, St = St, tmax = max(times)))
#> [1] 0.736408
with(filter(dt, method == "{risksetROC}"), IntegrateAUC(AUC = AUC, utimes = times, St = St, tmax = max(times)))
#> [1] 0.6469802
```

<sup>Created on 2024-04-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by tagteam** [comment]
Alessandro Gasparini ***@***.***> writes:

> Hi,
>
> I was trying to implement the [integrated
> AUC](https://pubmed.ncbi.nlm.nih.gov/15737082/)
> as an "overall" summary measure of time-varying AUC for survival
> outcomes, and came across the {risksetROC} package which seems to
> implement it. Side note: is this something that {riskRegression} can
> already calculate?

hmm, what would the target of the risk prediction model be in the case
where you want to have an overall summary measure? showing the whole
curve to a patient may be overwhelming for decision making.

if for other purposes, then AUC(t) has problems in the beginning of the
followup period when only a few events have happened (discrimination is
50% at time zero) and also towards the end of the followup period where
only few patients are at risk: so you would have to limit the time
period somehow. 

another issue is the interpretation of this overall summary measure: an
AUC of an AUC? if there is no nice interpretation then simply taking the
average AUC in a given time interval might work for just fine? but, with
crossing AUCs of two rival models/markers you would in both cases loose
information by averaging.

>
> After fiddling around with it, I noticed that it estimates
> time-varying AUC values that are very different compared to what
> reported by the `Score()` function from {riskRegression}, see e.g. the
> following example:
>
> ``` r
> library(reprex)
> library(rstpm2)
> #> Loading required package: survival
> #> Loading required package: splines
> #> 
> #> Attaching package: 'rstpm2'
> #> The following object is masked from 'package:survival':
> #> 
> #>     colon
> library(riskRegression)
> #> riskRegression version 2023.12.21
> library(risksetROC)
> #> Loading required package: MASS
> library(survival)
> library(devtools)
> #> Loading required package: usethis
>
> data(brcancer)
> mod <- coxph(
>   Surv(rectime, censrec == 1) ~ hormon + x1 + x2 + x3 + x4 + x5 + x6 + x7,
>   data = brcancer,
>   x = TRUE,
>   y = TRUE)
>
> CoxWeights(
>   marker = mod$linear.predictors,
>   Stime = brcancer$rectime,
>   status = brcancer$censrec,
>   predict.time = 300
> )$AUC
> #> [1] 0.659743
>
> Score(
>   list(mod),
>   formula = update(mod$formula, . ~ 1),
>   data = brcancer,
>   times = 300,
>   metrics = "auc"
> )
> #> 
> #> Metric AUC:
> #> 
> #> Results by model:
> #> 
> #>     model times    AUC  lower  upper
> #>    <fctr> <num> <char> <char> <char>
> #> 1:  coxph   300   74.1   66.4   81.9
> #> 
> #> NOTE: Values are multiplied by 100 and given in %.
> #> NOTE: The higher AUC the better.
> ```
>
> `CoxWeights()` from the {risksetROC} package reports an AUC of 0.659
> at 300 days, while `Score()` from the {riskRegression} package reports
> an AUC of 0.741. Am I missing something here? Or are these two not
> referring to the same AUC?
>

not sure what they do in risksetROC but the AUC calculated by CoxWeights is 0.75 for a marker
which is independent of the outcome: 

 ``` r
set.seed(8)
n <- 10000
time <- runif(n)
event <- rep(1,n)
X <- rnorm(n)
CoxWeights(
  marker = X,
  Stime = time,
  status = event,
  predict.time = .5
)$AUC
#  0.7609737
d <- data.frame(time = time,event = event,X = X)
Score(
  list(d$X),
  formula = Hist(time,event)~1,
  data = d,
  times = .5,
  metrics = "auc"
)
## Metric AUC:

## Results by model:

##      model times    AUC  lower  upper
## 1: numeric   0.5   49.9   48.8   51.0
## 
## NOTE: Values are multiplied by 100 and given in %.
## NOTE: The higher AUC the better.
```

**Comment by tagteam** [comment]
survivalROC is rather slow but in simulated data their result equals the
one from riskRegression (see below). not sure what the source of the small
difference in brcancer is. you could reduce the sample size of the
brcancer dataset or even easier construct a very small data set,
something with n=10 where you see a difference between riskRegression
and survivalROC ... 

``` r
library(survivalROC)
library(riskRegression)
set.seed(8)
n <- 1000
d <- sampleData(n,outcome = "survival")
d$time <- round(d$time,1)
with(d,survivalROC(
           marker = X6,
           Stime = time,
           status = event,
           predict.time = 0.5,
           method = "KM"
       )$AUC)
Score(
  list(d$X6),
  formula = Hist(time,event)~1,
  data = d,
  times = .5,
  metrics = "auc"
)
```

Alessandro Gasparini ***@***.***> writes:

> I also added a comparison with the {survivalROC} package, which computes different values to both {riskRegression} and {risksetROC}:
>
> ``` r
> library(rstpm2)
> #> Loading required package: survival
> #> Loading required package: splines
> #> 
> #> Attaching package: 'rstpm2'
> #> The following object is masked from 'package:survival':
> #> 
> #>     colon
> library(riskRegression)
> #> riskRegression version 2023.12.21
> library(risksetROC)
> #> Loading required package: MASS
> library(survival)
> library(devtools)
> #> Loading required package: usethis
> library(tidyverse)
> library(survivalROC)
>
> data(brcancer)
> mod <- coxph(
>   Surv(rectime, censrec == 1) ~ hormon + x1 + x2 + x3 + x4 + x5 + x6 + x7,
>   data = brcancer,
>   x = TRUE,
>   y = TRUE
> )
>
> times <- unique(brcancer$rectime[brcancer$censrec == 1])
>
> AUC_risksetROC <- map_dbl(.x = times, .f = function(t) {
>   CoxWeights(
>     marker = mod$linear.predictors,
>     Stime = brcancer$rectime,
>     status = brcancer$censrec,
>     predict.time = t
>   )$AUC
> })
>
> AUC_survivalROC <- map_dbl(.x = times, .f = function(t) {
>   survivalROC(
>     marker = mod$linear.predictors,
>     Stime = brcancer$rectime,
>     status = brcancer$censrec,
>     predict.time = t,
>     method = "KM"
>   )$AUC
> })
>
> AUC_riskRegression <- Score(
>   list(mod),
>   formula = update(mod$formula, . ~ 1),
>   data = brcancer,
>   times = times,
>   metrics = "auc"
> )$AUC$score$AUC
>
> St <- survfit(formula = update(mod$formula, . ~ 1), data = brcancer)
> St <- summary(St, times = times)$surv
>
> dt <- bind_rows(
>   data.frame(times, St, AUC = AUC_riskRegression, method = "{riskRegression}"),
>   data.frame(times, St, AUC = AUC_survivalROC, method = "{survivalROC}"),
>   data.frame(times, St, AUC = AUC_risksetROC, method = "{risksetROC}")
> )
>
> ggplot(dt, aes(x = times, y = AUC, color = method)) +
>   geom_line()
> ```
>
> ![](https://i.imgur.com/SkMYMa8.png)
>
> ``` r
>
> with(filter(dt, method == "{riskRegression}"), IntegrateAUC(AUC = AUC, utimes = times, St = St, tmax = max(times)))
> #> [1] 0.7491338
> with(filter(dt, method == "{survivalROC}"), IntegrateAUC(AUC = AUC, utimes = times, St = St, tmax = max(times)))
> #> [1] 0.736408
> with(filter(dt, method == "{risksetROC}"), IntegrateAUC(AUC = AUC, utimes = times, St = St, tmax = max(times)))
> #> [1] 0.6469802
> ```
>
> <sup>Created on 2024-04-15 with [reprex v2.1.0](https://reprex.tidyverse.org/)</sup>

-- 
7LL-2 What others think of you is none of your business.

**Comment by ellessenne** [comment]
Thanks for your feedback! The goal of computing the integrated AUC (in addition to plotting and reporting the time-varying AUC over time) would be to have an "overall" summary measure to ease the comparison between different models. This would be in addition to time-varying AUC plots, Brier scores plots, integrated Brier scores, and smooth calibration curves. 

Heagerty and Zheng (paper linked above) define the integrated AUC as:


$$
\int \widehat{AUC}(t) \hat{w}(t) \ dt
$$

where $\widehat{AUC}(t)$ is the estimated time-varying AUC and $\hat{w}(t)$ a certain weight function (they suggest using $\hat{w}(t) = 2 \hat{f}(t) \hat{S}(t) / (1 - \hat{S}^2(t))$ ), so essentially a weighted average of the time-varying AUC as you suggest? Maybe you are right, and presenting a mean time-varying AUC would be enough...

Also, agree with the issues of interpreting time-varying AUC during early/late follow-up times and with the issues of time-varying AUC that cross over time – hence I would still present this together with a plot of the entire AUC over time. 

Interesting that `CoxWeights()` returns such a high AUC for an independent marker – I reached out to the maintainer of {risksetROC}, which also maintains {survivalROC}. Will update back here when I hear back.

I will also try to find out why in the example with the breast cancer dataset the time-varying AUCs from {survivalROC} and {riskRegression} are different.

Many thanks once again for your feedback!

**Comment by tagteam** [comment]
here is a minimal example where the estimates differ. a quick look at
the source code of survivalROC::survivalROC() shows that they do not
calculate an IPCW estimator with weights obtained by the Kaplan-Meier
for the censoring distribution, but this is what riskRegression::Score()
does. 

``` r
dd <- data.frame(time = 1:4,status = c(1,0,1,0),x = c(1,3,4,2))
AUC_survivalROC <- survivalROC(
        marker = dd$x,
        Stime = dd$time,
        status = dd$status,
        predict.time = 3.8,
        method = "KM"
    )$AUC
AUC_riskRegression <- Score(list(dd$x),
                            formula = Hist(time,status)~1,
                            data = dd,
                            times = 3.8,
                            metrics = "auc")
## AUC_riskRegression$AUC$score$AUC
cbind(AUC_survivalROC,Score = AUC_riskRegression$AUC$score$AUC)
``` 

Alessandro Gasparini ***@***.***> writes:

> Thanks for your feedback! The goal of computing the integrated AUC (in
> addition to plotting and reporting the time-varying AUC over time)
> would be to have an "overall" summary measure to ease the comparison
> between different models. This would be in addition to time-varying
> AUC plots, Brier scores plots, integrated Brier scores, and smooth
> calibration curves.
>
> Heagerty and Zheng (paper linked above) define the integrated AUC as:
>
>
> $$
> \int \widehat{AUC}(t) \hat{w}(t) \ dt
> $$
>
> where $\widehat{AUC}(t)$ is the estimated time-varying AUC and
> $\hat{w}(t)$ a certain weight function (they suggest using $\hat{w}(t)
> = 2 \hat{f}(t) \hat{S}(t) / (1 - \hat{S}^2(t))$), so essentially a
> weighted average of the time-varying AUC as you suggest? Maybe you are
> right, and presenting a mean time-varying AUC would be enough...
>
> Also, agree with the issues of interpreting time-varying AUC during
> early/late follow-up times and with the issues of time-varying AUC
> that cross over time – hence I would still present this together with
> a plot of the entire AUC over time.
>
> Interesting that `CoxWeights()` returns such a high AUC for an
> independent marker – I reached out to the maintainer of {risksetROC},
> which also maintains {survivalROC}. Will update back here when I hear
> back.
>
> I will also try to find out why in the example with the breast cancer
> dataset the time-varying AUCs from {survivalROC} and {riskRegression}
> are different.
>
> Many thanks once again for your feedback!

-- 
7LL-1 Make peace with your past so it doesn’t spoil your present.

**Comment by paramita-sc** [comment]
Hello all!
Thank you for your question. I co-developed risksetROC and survivalROC. risksetROC measures incident/dynamic ROC and survivalROC measures cumulative/dynamic ROC. The time-dependent case definitions are different between them, but the time-dependent controls are the same between them. So essentially they are measuring two different targets of inference and I am not surprised that they are giving you different results. 

I am not familiar with the {riskRegression} package and cannot tell you whether it is trying to replicate incident/dynamic ROC or cumulative/dynamic ROC or an entire different target (yes there are several pairs of case/control definitions). But will be happy to be directed at relevant articles to learn about it.

Thank you!

**Comment by ellessenne** [comment]
Thanks for your feedback @tagteam and @paramita-sc! I figured it was different methods, I was mainly surprised by how different AUC values could be.

Empirically, I think {riskRegression}'s `Score()` (with `cens.method = "ipcw"` and `cens.model="km"`) is equivalent to {survivalROC} with `method = "KM"`.

FYI, I run a comparison with 2,000 simulated subjects and a completely independent marker with no prognostic value:

![Rplot](https://github.com/tagteam/riskRegression/assets/10330005/1f127853-014b-4164-907a-9414915f91c9)
