### ISSUE TITLE
IPCW with longitudinal predictors

### ISSUE THREAD

**Issue by glyden** [tagteam/riskRegression#57]
Is there any interface within riskRegression::Score to specify a censoring model that depends on longitudinal predictors (ie, time-dependent covariates)? For example, I'm wondering if expanding the `data` into start-stop format and include start and stop in the `formula` would be sufficient. Any guidance on how to do this appropriately using the package would be much appreciated. Thank you!

**Comment by tagteam** [comment]
no, there is none right now. theoretically, you can reduce bias and gain
efficiency by including covariates into the censoring model. here bias
is more important I guess. do you have
a good use-case?

Grace Lyden ***@***.***> writes:

> Is there any interface within riskRegression::Score to specify a
> censoring model that depends on longitudinal predictors (ie,
> time-dependent covariates)? For example, I'm wondering if expanding
> the `data` into start-stop format and include start and stop in the
> `formula` would be sufficient. Any guidance on how to do this
> appropriately using the package would be much appreciated. Thank you!

-- 
7LL-3 Time heals almost everything, give the time, some time.

**Comment by glyden** [comment]
Thanks for the reply!

My particular use-case would be comparing risk scores for organ allocation. These risk scores quantify a patient's probability of survival without transplant. I want to compare predictive performance between a few proposed risk scores. However, in the test data, many patients receive transplant before they die waiting and these tend to be the sickest patients so they are informatively censored. There are numerous time-varying prognostic measures in transplant data, which indicate that a patient is getting sicker and also give the patient increased priority for transplant. I would like to incorporate these time-varying prognostic measures into my inverse-probability-of-censoring weights for time-dependent AUC. 

I think this problem would apply broadly to survival risk scores with informative censoring that depends on longitudinal data. Conceptually, I am picturing the inverse-probability-of-censoring weights that are used in a marginal structural model, as described in Cole and Hernan (2008). However, I haven't found time-dependent AUC literature that presents this type of time-varying censoring weight or software to implement it.

Cole and Hernan (2008): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2732954/

**Comment by tagteam** [comment]
thanks for discussing this example. I confirm that riskRegression::Score
cannot do what you want. sorry

remark: I am not sure why you want to treat transplant events as censored. it
seems more appropriate to treat transplant as a competing risk. if the
sickest get "censored" the positivity assumption may fail unless there
are also equally sick patients who do not get a transplant ...

Grace Lyden ***@***.***> writes:

> Thanks for the reply!
>
> My particular use-case would be comparing risk scores for organ
> allocation. These risk scores quantify a patient's probability of
> survival without transplant. I want to compare predictive performance
> between a few proposed risk scores. However, in the test data, many
> patients receive transplant before they die waiting and these tend to
> be the sickest patients so they are informatively censored. There are
> numerous time-varying prognostic measures in transplant data, which
> indicate that a patient is getting sicker and also give the patient
> increased priority for transplant. I would like to incorporate these
> time-varying prognostic measures into my
> inverse-probability-of-censoring weights for time-dependent AUC.
>
> I think this problem would apply broadly to survival risk scores with
> informative censoring that depends on longitudinal data. Conceptually,
> I am picturing the inverse-probability-of-censoring weights that are
> used in a marginal structural model, as described in Cole and Hernan
> (2008). However, I haven't found time-dependent AUC literature that
> presents this type of time-varying censoring weight or software to
> implement it.
>
> Cole and Hernan (2008):
> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2732954/

-- 
7LL-4 No one is the reason for your happiness except you yourself.
