### ISSUE TITLE
weighted Fine-Gray regression competing risk models?

### ISSUE THREAD

**Issue by Ink-Mo** [tagteam/riskRegression#58]
Is there any function that can fit a weighted Fine-Gray models and caculated sHR(95CI), P Value?

**Comment by tagteam** [comment]
I don't know. note that FGR is a wrapper for cmprsk::crr. you could ask
over there.


Ink-Mo ***@***.***> writes:

> Is there any function that can fit a weighted Fine-Gray models and caculated sHR(95CI), P Value?

-- 
7LL-7 Smile, you don’t own all the problems in the world.

**Comment by Ink-Mo** [comment]
I've already tried, and it does not contain any arg for "weights".

**Comment by jinseob2kim** [comment]
@Ink-Mo You can use finegray model with`finegray` &  `coxph` function in `survival` package. `coxph` supports `weights` option

**Comment by Ink-Mo** [comment]
> @Ink-Mo You can use finegray model with`finegray` & `coxph` function in `survival` package. `coxph` supports `weights` option

I have  tried that. However, I found `coxph` only surpport cause- specific hazard ratio model with `weights` option, not for fine- gray hazard ratio model.

**Comment by jinseob2kim** [comment]
@Ink-Mo What about a multi-state model? This is also a competing risk analysis and is recommended by the `survival` package authors over the fine-gray model.  Weights can also be applied.  Here's an example and more details at https://cran.r-project.org/web/packages/survival/vignettes/compete.pdf

```r
library(survival)
mgus2$etime <- with(mgus2, ifelse(pstat==0, futime, ptime))
event <- with(mgus2, ifelse(pstat==0, 2*death, 1))
mgus2$event <- factor(event, 0:2, labels=c("censor", "pcm", "death"))
table(mgus2$event)
mfit2 <- coxph(Surv(etime, event) ~ sex, data=mgus2, id = id, weights = age)
```
result
```r
Call:
coxph(formula = Surv(etime, event) ~ sex, data = mgus2, weights = age, 
    id = id)

      
1:2        coef exp(coef) se(coef) robust se      z     p
  sexM -0.04622   0.95483  0.02276   0.19020 -0.243 0.808

      
1:3        coef exp(coef) se(coef) robust se     z        p
  sexM 0.233846  1.263450 0.007998  0.065781 3.555 0.000378

 States:  1= (s0), 2= pcm, 3= death 

Likelihood ratio test=865.2  on 2 df, p=< 2.2e-16
n= 1384, number of events= 975 
```

**Comment by Ink-Mo** [comment]
Yes, I know. One of the competing-risk models is called the cause-specific hazard model. Another competing-risk model is the Fine-Gray hazard model. The main difference between them is that in the Fine-Gray model, competing events are not treated as censored. When we are interested in absolute incidence, the subdistribution hazard model(Fine-Gray model) is more suitable.

**Comment by Ink-Mo** [comment]
> @Ink-Mo What about a multi-state model? This is also a competing risk analysis and is recommended by the `survival` package authors over the fine-gray model. Weights can also be applied. Here's an example and more details at https://cran.r-project.org/web/packages/survival/vignettes/compete.pdf
> 
> ```r
> library(survival)
> mgus2$etime <- with(mgus2, ifelse(pstat==0, futime, ptime))
> event <- with(mgus2, ifelse(pstat==0, 2*death, 1))
> mgus2$event <- factor(event, 0:2, labels=c("censor", "pcm", "death"))
> table(mgus2$event)
> mfit2 <- coxph(Surv(etime, event) ~ sex, data=mgus2, id = id, weights = age)
> ```
> 
> result
> 
> ```r
> Call:
> coxph(formula = Surv(etime, event) ~ sex, data = mgus2, weights = age, 
>     id = id)
> 
>       
> 1:2        coef exp(coef) se(coef) robust se      z     p
>   sexM -0.04622   0.95483  0.02276   0.19020 -0.243 0.808
> 
>       
> 1:3        coef exp(coef) se(coef) robust se     z        p
>   sexM 0.233846  1.263450 0.007998  0.065781 3.555 0.000378
> 
>  States:  1= (s0), 2= pcm, 3= death 
> 
> Likelihood ratio test=865.2  on 2 df, p=< 2.2e-16
> n= 1384, number of events= 975 
> ```

Yes, I know. One of the competing-risk models is called the cause-specific hazard model. Another competing-risk model is the Fine-Gray hazard model. The main difference between them is that in the Fine-Gray model, competing events are not treated as censored. When we are interested in absolute incidence, the subdistribution hazard model(Fine-Gray model) is more suitable.

**Comment by Ink-Mo** [comment]
> @Ink-Mo What about a multi-state model? This is also a competing risk analysis and is recommended by the `survival` package authors over the fine-gray model. Weights can also be applied. Here's an example and more details at https://cran.r-project.org/web/packages/survival/vignettes/compete.pdf
> 
> ```r
> library(survival)
> mgus2$etime <- with(mgus2, ifelse(pstat==0, futime, ptime))
> event <- with(mgus2, ifelse(pstat==0, 2*death, 1))
> mgus2$event <- factor(event, 0:2, labels=c("censor", "pcm", "death"))
> table(mgus2$event)
> mfit2 <- coxph(Surv(etime, event) ~ sex, data=mgus2, id = id, weights = age)
> ```
> 
> result
> 
> ```r
> Call:
> coxph(formula = Surv(etime, event) ~ sex, data = mgus2, weights = age, 
>     id = id)
> 
>       
> 1:2        coef exp(coef) se(coef) robust se      z     p
>   sexM -0.04622   0.95483  0.02276   0.19020 -0.243 0.808
> 
>       
> 1:3        coef exp(coef) se(coef) robust se     z        p
>   sexM 0.233846  1.263450 0.007998  0.065781 3.555 0.000378
> 
>  States:  1= (s0), 2= pcm, 3= death 
> 
> Likelihood ratio test=865.2  on 2 df, p=< 2.2e-16
> n= 1384, number of events= 975 
> ```

@jinseob2kim Yes, I know. One of the competing-risk models is called the cause-specific hazard model. Another competing-risk model is the Fine-Gray hazard model. The main difference between them is that in the Fine-Gray model, competing events are not treated as censored. When we are interested in absolute incidence, the subdistribution hazard model(Fine-Gray model) is more suitable.
